package Model;

/**
 * A mirror of the "product" table from the "schooldb" database.
 * It is the internal representation of the table.
 */
public class Product {
    private int productID;
    private String name;
    private int quantity;
    private double price;

    /**
     * The empty constructor is used by the SQL queries.
     * It creates an instance of a order without initializing its fields.
     */
    public Product() {}

    /**
     * A parameterized constructor is used to create an instance of a product with the following pre-set fields.
     * Besides these parameters, a product also has an unique identifying ID (the "productID" field).
     * This field is automatically generated by the inset query into the database.
     *
     * The pre-set parameters are:
     * @param name The name of the product. Stored as a STRING value
     * @param quantity The quantity which is currently in stock. Stored as an INTEGER
     * @param price The price of a unit piece of this product. Stored as a DOUBLE
     */
    public Product(String name, int quantity, double price) {
        this.name = name;
        this.quantity = quantity;
        this.price = price;
    }

    public int getProductID() {
        return productID;
    }

    public void setProductID(int productID) {
        this.productID = productID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }
}
